baseURL = "http://hugotestsite.flkdesign.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"

[params]
extracssfiles = ["/css/override.css"]

[[menu.main]]
name                   = "Home"
weight                 = 10
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Portfolio"
weight                 = 20
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "Blog"
weight                 = 30
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = 40
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Contact"
weight                 = 50
identifier             = "contact"
url                    = "/contact/"